# AMBIENTE PROD
server{
    listen 80;
    server_name localhost;
    resolver 127.0.0.11 ipv6=off valid=30s;
    set $backend_upstream http://sio-backend:3000;
    location / {
        proxy_pass http://fe-prod:80;
    }
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass $backend_upstream;
    }
}

# AMBIENTE TEST
server{
    listen 8080;
    resolver 127.0.0.11 ipv6=off valid=30s;
    set $backend_upstream http://sio-backend:3000;
    location / {
        proxy_pass http://fe-test:80;
    }
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass $backend_upstream;
    }
}

# AMBIENTE SVI
server{
    listen 8999;
    resolver 127.0.0.11 ipv6=off valid=30s;
    set $backend_upstream http://sio-backend:3000;
    location / {
        proxy_pass http://fe-sio:80;
    }
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass $backend_upstream;
    }
}
